lwr:

  # Publish all joint states -----------------------------------
  kuka_joint_state_controller:
    type: lwr_controllers/KUKAJointStateController
    publish_rate: 100  
    root_name: lwr_base_link
    tip_name: lwr_7_link

## OTHER CUSTOM CONTROLLERS LEFT HERE AS EXAMPLES
#  gravity_compensation_controller:
#    type: lwr_controllers/GravityCompensation
#    root_name: lwr_base_link
#    tip_name: lwr_7_link

  #   Joint Position Impedance Controllers
  joint_position_impedance_controller:
    type: lwr_controllers/JointPositionImpedanceController
    root_name: lwr_base_link
    tip_name: lwr_7_link
    stiffness_gains: 500
    damping_gains: .7


  # One Task Inverse Kinematics
  one_task_inverse_kinematics:
    type: lwr_controllers/OneTaskInverseKinematics
    root_name: lwr_base_link
    tip_name: lwr_7_link


  # Inverse Dynamics Controllers
#  inverse_dynamics_controller:
#    type: lwr_controllers/InverseDynamicsController
#    root_name: lwr_base_link
#    tip_name: lwr_7_link

  # Computed Torque Controllers
#  computed_torque_controller:
#    type: lwr_controllers/ComputedTorqueController
#    root_name: lwr_base_link
#    tip_name: lwr_7_link




